sonar.organization=maekeshiadanieltoledo-collab
sonar.projectKey=maekeshiadanieltoledo-collab_Inventory-System
sonar.sources=.
sonar.host.url=https://sonarcloud.io
sonar.javascript.lcov.reportPaths=coverage/lcov.info
